### ISSUE TITLE
Broken link on "Introduction" page

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity#19]
Here's a screenshot of the link that goes to a GitHub 404:

<img width="1351" alt="image" src="https://github.com/microsoft/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity/assets/392297/fcae6d17-b13b-4b86-9e38-1cc63bf0b62b">

**Comment by feaselkl** [comment]
Looks like this is an issue in index.md. Chris's image has the appropriate URL. If nobody gets to this before this evening, I'll fix the link.
