### ISSUE TITLE
ex5 - should we introduce a security issue

### ISSUE THREAD

**Issue by danielstocker** [microsoft/TechExcel-Implementing-DevOps-practices-to-accelerate-developer-productivity#32]
Wondering if we should introduce an issue that GHAS will catch and then ask participants to fix it with Copilot. If that's too complex to achieve then let's not do this. We've already added plenty of Copilot Chat interactions.

**Comment by feaselkl** [comment]
There is already an issue we introduced that GHAS finds in CodeQL scans. Is there a separate kind of issue you'd want to introduce? If so, any thoughts on the specific issue?

**Comment by danielstocker** [comment]
oh no that's all good then. i must have overlooked this while browsing.
